
@startuml
!include <azure/AzureCommon>
!include <azure/Databases/AzureCosmosDb>
!include <azure/Containers/AzureContainerInstance>
!include <azure/Containers/AzureKubernetesService>
!include <azure/Compute/AzureBatch>
!include <azure/Web/AzureAPIManagement>

left to right direction
skinparam linetype ortho

AzureAPIManagement(ApiGateway, "API Management", "AzureAPIManagement")
AzureKubernetesService(CriacaoCarrinho, "API Criação de Carrinho", "Spring Boot; 3 TUs")
AzureKubernetesService(AtualizacaoCarrinho, "API Atualização de Carrinho", "Spring Boot; 3 TUs")
AzureBatch(ProcessoElegibilidade, "Batch Elegibilidade", "Spring Batch; 3 TUs")
AzureBatch(ProcessoDisparoCampanhas, "Batch Disparo de Campanhas", "Spring Batch; 3 TUs")
AzureCosmosDb(database, "Database", "1,000 RUs")

ApiGateway --> CriacaoCarrinho
ApiGateway --> AtualizacaoCarrinho
CriacaoCarrinho --> database
AtualizacaoCarrinho --> database
ProcessoElegibilidade --> database
ProcessoDisparoCampanhas --> database

@enduml


